import { When } from '@badeball/cypress-cucumber-preprocessor';

/* eslint-disable tsdoc/syntax */
/**
 * When I screenshot:
 *
 * ```gherkin
 * When I screenshot
 * ```
 *
 * When I screenshot with filename:
 *
 * ```gherkin
 * When I screenshot {string}
 * ```
 *
 * @example
 *
 * Take a screenshot with an autogenerated filename:
 *
 * ```gherkin
 * When I screenshot
 * ```
 *
 * > The screenshot will be stored in the [screenshots folder](https://docs.cypress.io/guides/references/configuration#Folders-Files) (e.g., `cypress/screenshots`) and path to the spec file.
 *
 * Take a screenshot with a specified filename:
 *
 * ```gherkin
 * When I screenshot "path/to/screenshot"
 * ```
 *
 * > When passed a path, the folder structure will be created.
 *
 * @remarks
 *
 * Takes a screenshot of the application under test. See [naming conventions](https://docs.cypress.io/api/commands/screenshot#Naming-conventions).
 */
/* eslint-enable tsdoc/syntax */
export function When_I_screenshot(filename: string) {
  cy.screenshot(filename);
}

When('I screenshot', When_I_screenshot);
When('I screenshot {string}', When_I_screenshot);
