Feature: httpbin
  Scenario: Form
    Given I visit "https://httpbin.org/forms/post"
    When I find element by label text "Customer name"
      And I type "John Smith"
    When I find input by label text "Telephone"
      And I type "1234567890"
    When I find element by label text "E-mail address"
      And I type "john.smith@example.com"
    When I click on label "Small"
      And I click on label "Bacon"
      And I click on label "Extra Cheese"
    When I find input by label text "Preferred delivery time"
      And I type "12:00"
    When I find element by label text "Delivery instructions"
      And I type "Please leave the box on the porch."
