Feature: httpbin
  Scenario: Form
    Given I visit "https://httpbin.org/forms/post"
    When I find input by label text "Customer name"
      And I type "John Smith"
    Then I see input value "John Smith"
    When I find inputs by name "custtel"
      And I type "1234567890"
    Then I find input by label text "Telephone"
      And I see value "1234567890"
      And I see input value "1234567890"
    When I find input by name "custemail"
      And I type "john.smith@example.com"
    Then I find input by label text "E-mail address"
      And I see value "john.smith@example.com"
      And I see input value "john.smith@example.com"
    When I click on label "Small"
      And I click on label "Bacon"
      And I click on label "Extra Cheese"
    When I find elements by label text "Preferred delivery time"
      And I count 1 element
    When I find element by label text "Preferred delivery time"
      And I type "12:00"
    When I find element by name "comments"
      And I type "Please leave the box on the porch."
    Then I see textarea value "Please leave the box on the porch."
      And I see textarea value contains "Please leave the box"
